{% set name = "torch_cluster" %}
{% set version = "1.5.9" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96209e9f3f073c8e7fe91fbf7dd2cdd8655622d14dfc95a7618b4893a658dca5

build:
  number: 1
  skip: true  # [win or cuda_compiler_version == 'None' or cuda_compiler_version == '10.2']
  script:
    - export FORCE_CUDA="1"    # [linux64 and cuda_compiler_version != 'None']
    - export CC="$GCC"   # [linux64 and cuda_compiler_version != 'None']
    - export NVCC_FLAGS="--compiler-bindir=${CC}"    # [linux64 and cuda_compiler_version != 'None']
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - python
    - pytorch
    - pytorch =*={{ torch_proc_type }}*
    # hmaarrfk 20220312: build 1 has the correct run exports
    - pytorch >=1.10.0=*_1
    - scipy
    - setuptools
    - pytest-runner
    - pip
  run:
    - python
    - scipy
    - pytest
    - pytest-cov
  run_constrained:
    - pytorch =*={{ torch_proc_type }}*
    
test:
  imports:
    - torch_cluster

about:
  home: https://github.com/rusty1s/pytorch_cluster
  summary: PyTorch Extension Library of Optimized Graph Cluster Algorithms
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_cluster

extra:
  recipe-maintainers:
    - mxr-conda
    - dsangillo
