{% set name = "torch_cluster" %}
{% set version = "1.5.8" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0a32f63faac40a026ab1e9da31f6babdb4d937e53be40bd1c91d9b5a286eee6

build:
  number: 0
  skip: true  # [win or cuda_compiler_version == 'None' or cuda_compiler_version == '10.2']
  script:
    - export FORCE_CUDA="1"    # [linux64 and cuda_compiler_version != 'None']
    - export CC="$GCC"   # [linux64 and cuda_compiler_version != 'None']
    - export NVCC_FLAGS="--compiler-bindir=${CC}"    # [linux64 and cuda_compiler_version != 'None']
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - python
    - pytorch
    - scipy
    - setuptools
    - pytest-runner
    - pip
  run:
    - python
    - pytorch
    - scipy
    - pytest
    - pytest-cov

test:
  imports:
    - torch_cluster

about:
  home: https://github.com/rusty1s/pytorch_cluster
  summary: PyTorch Extension Library of Optimized Graph Cluster Algorithms
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_cluster

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
